"""executable UI test generator (Playwright TS).

Mirrors the API generator but emits browser-driven specs. Uses
semantic locators (`getByRole`, `getByLabel`, `getByText`) by default and
refuses to bake in brittle CSS/XPath. Failures produce screenshot + trace
artifacts thanks to the Playwright config snippet shipped alongside the spec.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional

from ..errors import UsageError
from ..plan_v2 import PlanItem
from ._escape import js_comment_text, js_str, validate_ui_assertion_token


@dataclass(frozen=True)
class GeneratedUiTest:
    candidate_id: str
    relative_path: str
    content: str
    runner: str = "playwright-ts"


# Selectors the gate rejects unless explicitly justified in plan notes.
_BRITTLE_SELECTOR_HINTS = ("div >", ".css-", "[data-test=", "xpath=", "/html/")


def generate_ui_test(
    item: PlanItem,
    *,
    tests_dir: str = "tests",
    ui_url_env: str = "UI_BASE_URL",
    credentials_env: Optional[str] = None,
    coverage_floor: bool = False,
) -> GeneratedUiTest:
    if item.test_type != "ui":
        raise UsageError(
            f"generate_ui_test: only test_type='ui' supported, got {item.test_type!r}"
        )
    if item.decision != "generate_now":
        raise UsageError(
            f"generate_ui_test: only decision='generate_now' supported, got {item.decision!r}"
        )
    if not item.source_refs:
        raise UsageError("generate_ui_test requires at least one source_ref")
    if not item.expected_assertion.strip():
        raise UsageError("generate_ui_test requires expected_assertion")
    if not item.target_page:
        raise UsageError("generate_ui_test requires target_page")
    # Guard: target_page must be relative or http(s).
    if "://" in item.target_page and not item.target_page.startswith(("http://", "https://")):
        raise UsageError(f"target_page has unsupported scheme: {item.target_page!r}")
    # Reject brittle selectors leaking through the plan.
    for note in (item.notes or []):
        if any(hint in note for hint in _BRITTLE_SELECTOR_HINTS):
            raise UsageError(
                f"plan notes hint at brittle selector ({note!r}); use getByRole/Label/Text"
            )

    slug = _slug(item.title) or "ui"
    file_name = f"{item.candidate_id.lower()}-{slug}.spec.ts"
    rel_path = f"{tests_dir.rstrip('/')}/ui/{file_name}"

    body = _render_ui_spec(
        item=item,
        ui_url_env=ui_url_env,
        credentials_env=credentials_env,
        coverage_floor=coverage_floor,
    )
    return GeneratedUiTest(candidate_id=item.candidate_id, relative_path=rel_path, content=body)


def generate_ui_tests(
    items: Iterable[PlanItem],
    *,
    tests_dir: str = "tests",
    ui_url_env: str = "UI_BASE_URL",
    credentials_env: Optional[str] = None,
    coverage_floor: bool = False,
) -> List[GeneratedUiTest]:
    out: List[GeneratedUiTest] = []
    for item in items:
        if item.test_type != "ui" or item.decision != "generate_now":
            continue
        out.append(
            generate_ui_test(
                item,
                tests_dir=tests_dir,
                ui_url_env=ui_url_env,
                credentials_env=credentials_env,
                coverage_floor=coverage_floor,
            )
        )
    return out


def _slug(text: str) -> str:
    s = text.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s[:60]


def _render_ui_spec(
    *,
    item: PlanItem,
    ui_url_env: str,
    credentials_env: Optional[str],
    coverage_floor: bool = False,
) -> str:
    refs = "\n".join(f" *   - {js_comment_text(ref)}" for ref in item.source_refs)
    expected = js_comment_text(item.expected_assertion)
    # Issue #88 — load the operator-provided storageState into the
    # browser context BEFORE the test runs. The previous version called
    # `context.storageState({ path })` which SAVES state, not loads it.
    auth_storage = ""
    test_use_storage = ""
    if credentials_env:
        test_use_storage = (
            "// Issue #88 — load auth state from operator-provided file.\n"
            "// Empty env var means the test runs unauthenticated.\n"
            f"const _AUTH_STATE_PATH = process.env[{js_str(credentials_env + '_STATE_PATH')}];\n"
            "if (_AUTH_STATE_PATH) {\n"
            "  test.use({ storageState: _AUTH_STATE_PATH });\n"
            "}\n\n"
        )
    target_page = item.target_page or "/"
    assertion_hint = _render_ui_assertions(item)
    test_title = f"{item.candidate_id} — {item.title}"
    floor_setup, floor_teardown = _render_coverage_floor(item, coverage_floor)
    return f"""// AUTO-GENERATED by Agentic OS UI generator.
// candidate: {js_comment_text(item.candidate_id)}
// generator: playwright-ts
//
/**
 * Sources:
{refs}
 *
 * Expected behavior (verbatim from TEST-PLAN):
 *   {expected}
 *
 * Selectors policy: getByRole / getByLabel / getByText only. CSS/XPath
 * fall-backs are flagged by the review gate. Do not weaken the assertion
 * below without an operator decision recorded in the database.
 */

import {{ test, expect }} from '@playwright/test';

const UI_BASE_URL = process.env[{js_str(ui_url_env)}];
if (!UI_BASE_URL) {{
  throw new Error({js_str(ui_url_env + " env var is required to run this test")});
}}

test.use({{ trace: 'retain-on-failure', screenshot: 'only-on-failure' }});

{test_use_storage}test({js_str(test_title)}, async ({{ page }}) => {{
  const targetPage = {js_str(target_page)};
{floor_setup}  await page.goto(new URL(targetPage, UI_BASE_URL).toString());

  // Plan-derived expectation — DO NOT weaken without operator decision.
  // {expected}
  {assertion_hint}
{floor_teardown}}});
"""


# Issue #230 — coverage-floor companion blocks. Each emits a fixed marker
# string that the reviewer (issue #233) greps to count coverage breadth
# without having to read the test logic. Soft asserts (`expect.soft`)
# never mask the primary plan assertion.
def _render_coverage_floor(item: PlanItem, enabled: bool) -> tuple[str, str]:
    if not enabled:
        return "", ""
    notes = {n.strip() for n in (item.notes or [])}
    setup_lines: List[str] = []
    teardown_lines: List[str] = []

    # Console + pageerror listener — captures uncaught JS exceptions and
    # console.error calls so the test fails soft on browser-side regressions.
    setup_lines.append("  // agentic-os:floor:console")
    setup_lines.append("  const _consoleErrors: string[] = [];")
    setup_lines.append("  page.on('pageerror', (err) => { _consoleErrors.push(`pageerror: ${err.message}`); });")
    setup_lines.append("  page.on('console', (msg) => {")
    setup_lines.append("    if (msg.type() === 'error') { _consoleErrors.push(`console.error: ${msg.text()}`); }")
    setup_lines.append("  });")
    teardown_lines.append("  // agentic-os:floor:console")
    teardown_lines.append("  expect.soft(_consoleErrors, 'TECH: browser console must not error').toEqual([]);")

    # Network listener — failed requests including 5xx + ERR_* + DNS.
    setup_lines.append("  // agentic-os:floor:network")
    setup_lines.append("  const _requestFailures: string[] = [];")
    setup_lines.append("  page.on('requestfailed', (req) => {")
    setup_lines.append("    _requestFailures.push(`${req.method()} ${req.url()} → ${req.failure()?.errorText ?? 'unknown'}`);")
    setup_lines.append("  });")
    setup_lines.append("  page.on('response', (res) => {")
    setup_lines.append("    if (res.status() >= 500) { _requestFailures.push(`${res.request().method()} ${res.url()} → ${res.status()}`); }")
    setup_lines.append("  });")
    teardown_lines.append("  // agentic-os:floor:network")
    teardown_lines.append("  expect.soft(_requestFailures, 'TECH: network requests must not 5xx / fail').toEqual([]);")

    # A11y smoke — axe-core dynamic import, fail-soft when the dep is
    # absent (the dep is optional in the operator's test workspace).
    teardown_lines.append("  // agentic-os:floor:a11y")
    teardown_lines.append("  try {")
    teardown_lines.append("    const { AxeBuilder } = await import('@axe-core/playwright');")
    teardown_lines.append("    const _axeResults = await new AxeBuilder({ page }).analyze();")
    teardown_lines.append("    const _critical = _axeResults.violations.filter((v) => v.impact === 'critical' || v.impact === 'serious');")
    teardown_lines.append("    expect.soft(_critical, 'TECH: no critical/serious a11y violations').toEqual([]);")
    teardown_lines.append("  } catch (e) {")
    teardown_lines.append("    /* @axe-core/playwright not installed — coverage floor a11y skipped */")
    teardown_lines.append("  }")

    # Link-walk — head-fetch anchors in viewport. Opt-out via notes.
    if "no-link-walk" not in notes:
        teardown_lines.append("  // agentic-os:floor:link-walk")
        teardown_lines.append("  const _hrefs = await page.locator('a[href]').evaluateAll((els) =>")
        teardown_lines.append("    els.map((e) => (e as HTMLAnchorElement).href).filter((h) => /^https?:\\/\\//.test(h))")
        teardown_lines.append("  );")
        teardown_lines.append("  const _brokenLinks: string[] = [];")
        teardown_lines.append("  for (const _href of _hrefs.slice(0, 20)) {")
        teardown_lines.append("    try {")
        teardown_lines.append("      const _resp = await page.request.head(_href, { failOnStatusCode: false, timeout: 5000 });")
        teardown_lines.append("      if (_resp.status() >= 400) { _brokenLinks.push(`${_href} → ${_resp.status()}`); }")
        teardown_lines.append("    } catch (_e) { /* skip unreachable */ }")
        teardown_lines.append("  }")
        teardown_lines.append("  expect.soft(_brokenLinks, 'TECH: link integrity').toEqual([]);")

    return "\n".join(setup_lines) + "\n\n", "\n" + "\n".join(teardown_lines) + "\n"


def _render_ui_assertions(item: PlanItem) -> str:
    """Generate UI assertions from the plan's expected_assertion text.

    The plan text drives behavior — we look for hints like
    `URL must contain /orders/<id>` or `text "Order created"`.
    """
    expected = item.expected_assertion
    lines: List[str] = []
    url_match = re.search(r"URL\s+(?:must\s+)?(?:contain|equal|match)\s+([^\s]+)", expected, re.IGNORECASE)
    text_match = re.search(r"text\s+[\"']([^\"']+)[\"']", expected, re.IGNORECASE)
    role_match = re.search(r"role\s+[\"']([^\"']+)[\"']\s+name\s+[\"']([^\"']+)[\"']", expected, re.IGNORECASE)
    if url_match:
        url_token = validate_ui_assertion_token(url_match.group(1))
        lines.append(f"await expect(page).toHaveURL(new RegExp({js_str(url_token)}));")
    if role_match:
        lines.append(
            f"await expect(page.getByRole({js_str(role_match.group(1))}, "
            f"{{ name: {js_str(role_match.group(2))} }})).toBeVisible();"
        )
    if text_match:
        lines.append(f"await expect(page.getByText({js_str(text_match.group(1))})).toBeVisible();")
    if not lines:
        raise UsageError(
            f"ui generator requires URL, text, or role/name assertion in expected_assertion for {item.candidate_id}"
        )
    return "\n  ".join(lines)
