#!/usr/bin/env bash
# QualityCat — Reports Adapter
#
# Copies Gradle / Cucumber / Allure outputs from build/ to reports/ (the contest
# deliverable directory). Run after every test execution so reports/ is always
# fresh for jury inspection.
#
# Usage:
#   ./scripts/copy-reports.sh            Copy default set (Cucumber HTML, JUnit XML, Allure HTML).
#   ./scripts/copy-reports.sh --clean    Wipe reports/ before copy.
#   ./scripts/copy-reports.sh --help     Show this help.
#
# Outputs:
#   reports/
#   ├── README.md                — quick overview + how to read reports.
#   ├── cucumber/                — Cucumber HTML report.
#   ├── junit/                   — JUnit XML (CI-friendly).
#   ├── allure/                  — Allure static HTML site (open allure/index.html).
#   └── summary.md               — pass/fail counts, generated at run-time.

set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"
BUILD_DIR="$PROJECT_ROOT/build"
REPORTS_DIR="$PROJECT_ROOT/reports"

usage() {
  sed -n '2,18p' "$0" | sed 's/^# //; s/^#//'
}

clean=0
case "${1:-}" in
  --help|-h) usage; exit 0 ;;
  --clean)   clean=1 ;;
  "") ;;
  *) echo "Unknown flag: $1" >&2; usage; exit 2 ;;
esac

if (( clean )); then
  rm -rf "$REPORTS_DIR"
fi
mkdir -p "$REPORTS_DIR/cucumber" "$REPORTS_DIR/junit" "$REPORTS_DIR/allure"

copy_if_exists() {
  local src="$1" dest="$2"
  if [[ -e "$src" ]]; then
    rm -rf "$dest"
    mkdir -p "$(dirname "$dest")"
    cp -R "$src" "$dest"
    echo "  copied: $src → $dest"
  else
    echo "  missing: $src (skipped)"
  fi
}

echo ">>> Copying reports from $BUILD_DIR → $REPORTS_DIR"

# Cucumber HTML (Gradle test task, default location)
copy_if_exists "$BUILD_DIR/reports/tests/test"          "$REPORTS_DIR/cucumber"
# Cucumber plugin HTML (cucumber.publish.quiet=true setup)
copy_if_exists "$BUILD_DIR/reports/cucumber"            "$REPORTS_DIR/cucumber-plugin"
# JUnit XML
copy_if_exists "$BUILD_DIR/test-results/test"           "$REPORTS_DIR/junit"
# Allure static site
copy_if_exists "$BUILD_DIR/reports/allure-report"       "$REPORTS_DIR/allure"
# Issue #99 — Playwright artifacts. Multiple toolchain conventions:
#   npx @playwright/test default: ./test-results (traces, screenshots)
#                                  + ./playwright-report (HTML)
#   JSON reporter:                 ./playwright-report.json
copy_if_exists "test-results"                           "$REPORTS_DIR/playwright/test-results"
copy_if_exists "playwright-report"                      "$REPORTS_DIR/playwright/html"
if [[ -f "playwright-report.json" ]]; then
  mkdir -p "$REPORTS_DIR/playwright"
  cp -f "playwright-report.json" "$REPORTS_DIR/playwright/report.json"
  echo "  copied: playwright-report.json → $REPORTS_DIR/playwright/report.json"
fi

# Summary file
SUMMARY="$REPORTS_DIR/summary.md"
generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Count JUnit results if XML present
pass=0; fail=0; skip=0; total=0
if compgen -G "$REPORTS_DIR/junit/*.xml" > /dev/null; then
  for f in "$REPORTS_DIR/junit"/*.xml; do
    t="$(grep -oE 'tests="[0-9]+"' "$f" | head -1 | grep -oE '[0-9]+' || echo 0)"
    f_="$(grep -oE 'failures="[0-9]+"' "$f" | head -1 | grep -oE '[0-9]+' || echo 0)"
    s_="$(grep -oE 'skipped="[0-9]+"' "$f" | head -1 | grep -oE '[0-9]+' || echo 0)"
    total=$((total + t))
    fail=$((fail + f_))
    skip=$((skip + s_))
  done
  pass=$((total - fail - skip))
fi

cat > "$SUMMARY" <<EOF
# Test Run Summary

- Generated at: $generated_at
- Total: $total
- Passed: $pass
- Failed: $fail
- Skipped: $skip

## Where to look

- Cucumber HTML — \`cucumber/index.html\`
- Allure static site — \`allure/index.html\` (open in browser, no server needed)
- JUnit XML — \`junit/*.xml\` (CI consumption)

## Known-bug failures

Failures tagged \`@known-bug\` are expected (app defects logged under \`bugs/\`).
Unexpected reds (no \`@known-bug\` tag) indicate test gaps or regressions.

See top-level \`bugs/README.md\` for the bug index.
EOF

# Boilerplate README inside reports/ if missing
if [[ ! -f "$REPORTS_DIR/README.md" ]]; then
  cat > "$REPORTS_DIR/README.md" <<'EOF'
# Reports

This directory is regenerated by `./scripts/copy-reports.sh` after each test run.

- `cucumber/` — Cucumber HTML report.
- `junit/` — JUnit XML files (CI-friendly).
- `allure/` — Allure static HTML site. Open `allure/index.html`.
- `summary.md` — pass/fail counts for the last run.

Do not edit by hand. To refresh: `./scripts/copy-reports.sh --clean` then `./run-tests.sh`.
EOF
fi

echo ">>> Done. Summary: $SUMMARY"
