"""Patch generator for operator work items .

Reads ``TEST-PLAN.md`` from ``agentic-os-runtime/plans/<work-item-id>/`` and produces
a deterministic, additive unified diff that creates a single new test
skeleton file under ``tests/generated/<work-item-id>.spec.md`` (relative to
the repo root).

The patch is written to ``agentic-os-runtime/patches/<work-item-id>/<hash>.patch``,
registered as a ``work_item_artifacts.kind='patch'`` and the work item
transitions to ``implementing``. The patch is never applied here — apply
happens only through ``run review-gate --apply-patch`` after an explicit
``APPROVE`` verdict (``gates.merge_patch_if_approved``).
"""
from __future__ import annotations

import hashlib
import json
import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from .errors import UsageError
from .events import EventLog
from .paths import RuntimePaths
from .time_utils import now_iso
from .work_items import (
    get_work_item,
    register_work_item_artifact,
    update_work_item_status,
)


SKELETON_REL_DIR = "tests/generated"


@dataclass(frozen=True)
class PatchPlan:
    target_rel_path: str
    body: str


def _implement_idempotency_key(
    work_item_id: str, family: str, specs: Sequence[Any]
) -> str:
    """Deterministic identity for one implementer fan-out work-unit (#362).

    Mirrors ``_run_tests_idempotency_key``: a stable sha256 over the sorted,
    canonical JSON of the unit's identity. A rerun of the same family on the
    same work item over the same approved surfaces yields the SAME key, so a
    duplicate generation is *detectable* rather than silently re-emitted. The
    key is order-independent (surfaces are sorted) — the fan-out merge order
    can never perturb it — and surface-sensitive, so a changed candidate set
    changes the key. It keys on the work-unit's *inputs* (candidate id + target
    path), not the generated bytes, so it stays the unit's identity rather than
    a hash of its output.
    """
    payload = {
        "workflow": "implement-tests",
        "work_item_id": work_item_id,
        "family": family,
        "surfaces": sorted(
            [getattr(s, "candidate_id", ""), getattr(s, "relative_path", "")]
            for s in specs
        ),
    }
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True).encode("utf-8")
    ).hexdigest()
    return f"implement-tests:{family}:{digest}"


def _detect_path_collisions(specs: Sequence[Any]) -> List[str]:
    """Output paths claimed by more than one fan-out work-unit (#360/#362).

    Conflict detection for the implementer fan-out: every unit must own a
    DISJOINT output file set so the merge is a fixed-order concatenation with
    no cross-unit overwrite. Families are disjoint by construction today, so
    this returns ``[]``; it exists to stop a future finer-grained fan-out (per
    feature file) from silently merging two units onto the same spec path. The
    result is sorted for a deterministic, byte-stable error message. On-disk
    collisions with PRE-EXISTING files are a separate concern handled
    deterministically by ``_suffix_until_free``.
    """
    rel_paths = [getattr(s, "relative_path", "") for s in specs]
    return sorted({p for p in rel_paths if p and rel_paths.count(p) > 1})


def implement_tests_for_work_item(
    conn: sqlite3.Connection,
    paths: RuntimePaths,
    events: EventLog,
    *,
    work_item_id: str,
) -> Dict[str, Any]:
    work_item = get_work_item(conn, work_item_id)
    if work_item is None:
        raise UsageError(f"unknown task id: {work_item_id}")
    plan_path = paths.runtime_root / "plans" / work_item_id / "TEST-PLAN.md"
    if not plan_path.exists():
        raise UsageError(
            f"TEST-PLAN.md is missing for {work_item_id}; run `task plan` first"
        )

    plan_text = plan_path.read_text(encoding="utf-8")
    skeleton = build_skeleton_patch(
        work_item_id=work_item_id,
        title=work_item["title"],
        priority=work_item["priority"],
        sut_root=work_item["sut_root"],
        plan_text=plan_text,
    )

    project_id = work_item.get("project_id") or "default"
    generated_v2 = _try_generate_v2(conn, paths, events, work_item_id, project_id)
    executable_specs: list[tuple[str, str]] = generated_v2.pop(
        "_executable_specs", []
    )
    # Issue #329 — extend-in-place entries: tuples of
    # ``(existing_rel_path, extracted_test_block, fallback_rel_path,
    # fallback_full_content)``. The caller renders these as modify-file
    # diffs against the spec already on disk so a surface gaining a new
    # assertion bucket produces zero new files. The fallback pair recovers
    # the surface as a full sibling spec when the target file is missing
    # (operator deleted it) — the extracted block alone has no imports /
    # env setup and would land an invalid Playwright spec.
    executable_extends: list[tuple[str, str, str, str]] = generated_v2.pop(
        "_executable_extends", []
    )
    # Issue #319/#320 (Codex P1) — build a *pending* coverage manifest from the
    # generation run. It is written beside the patch below and ingested into the
    # ledger only when `apply-patch` actually lands the spec files, so a patch
    # rejected by review-gate or never applied does not leave a ghost surface
    # in the ledger that would block regeneration.
    coverage_entries: list[dict] = []
    coverage = generated_v2.pop("_coverage", None)
    if coverage:
        try:
            from .coverage_ledger import build_coverage_entries

            coverage_entries = build_coverage_entries(
                coverage.get("plan_items", []),
                coverage.get("generated_tests", []),
                project_id=project_id,
                work_item_id=work_item_id,
                run_id=coverage.get("run_id"),
            )
            # Issue #329 — for extend candidates the ledger row must record
            # the *existing* shared spec_path (the file we just appended to),
            # not the path the generator would have created. The generator
            # cannot know about prior coverage so it always builds a fresh
            # relative_path; we patch the entries here using the override map
            # returned by ``_try_generate_v2``.
            overrides = coverage.get("spec_path_overrides") or {}
            if overrides:
                for entry in coverage_entries:
                    cid = entry.get("candidate_id")
                    if isinstance(cid, str) and cid in overrides:
                        entry["spec_path"] = overrides[cid]
        except Exception as exc:  # building entries is best-effort, never blocks
            events.write(
                "work_item.coverage_ledger_error",
                payload={"work_item_id": work_item_id, "error": str(exc)},
            )

    # Issue #320 — every requested surface was already covered: an idempotent
    # no-op. Emit no patch (a skeleton would be a duplicate artifact), leave the
    # work item status untouched, and report the skipped surfaces.
    if generated_v2.get("idempotent_noop"):
        events.write(
            "work_item.implement_idempotent_noop",
            actor="operator",
            payload={
                "work_item_id": work_item_id,
                "skipped_surfaces": generated_v2.get("skipped_surfaces", []),
            },
        )
        return {
            "work_item_id": work_item_id,
            "status": work_item["status"],
            "patch_path": None,
            "target_path": None,
            "executable_targets": [],
            "artifacts": [],
            "generated_v2": generated_v2,
            "executable_tests_generated": False,
            "idempotent_noop": True,
            "skipped_surfaces": generated_v2.get("skipped_surfaces", []),
            "next_action": generated_v2.get("next_action"),
        }

    has_executable_patch = bool(executable_specs or executable_extends) and not generated_v2.get(
        "needs_operator_decision"
    )

    # Issue #72 — when the v2 generator emits real executable test files,
    # the patch returned to the operator must contain those files. The
    # legacy skeleton path stays as the fallback only when no executable
    # tests were generated, so the apply step always creates runnable
    # tests.
    #
    # Issue #223 — repeat runs of `implement-tests` previously failed with
    # `refusing to overwrite existing file via patch` whenever the target
    # already existed on disk. The collision is now resolved by appending a
    # numeric suffix (`*.2.spec.ts`, `*.3.spec.ts`, ...) so operators can
    # regenerate or add scenarios without manually deleting prior tests.
    if has_executable_patch:
        resolved_specs: list[tuple[str, str]] = []
        # Issue #331 — `_suffix_until_free` may rewrite the on-disk target
        # (e.g. `foo.spec.ts` → `foo.2.spec.ts`) when an earlier run already
        # placed a spec at the original path. `coverage_entries` was built
        # from the unsuffixed `GeneratedTest.relative_path`, so without this
        # map the ledger would record a `spec_path` that does not exist on
        # disk after apply. Build an old→new map and rewrite the manifest
        # below before it is persisted.
        suffix_map: Dict[str, str] = {}
        for rel_target, body in executable_specs:
            original_target = rel_target
            rel_target = _suffix_until_free(paths.repo_root, rel_target)
            if rel_target != original_target:
                suffix_map[original_target] = rel_target
            resolved_specs.append((rel_target, body))
        if suffix_map and coverage_entries:
            for entry in coverage_entries:
                sp = entry.get("spec_path")
                if isinstance(sp, str) and sp in suffix_map:
                    entry["spec_path"] = suffix_map[sp]
        # Issue #329 — modify-file diffs for in-place extensions. We read
        # the existing on-disk content (must match `--- a/...` exactly for
        # `git apply` to accept the hunk), append the extracted test block
        # with a sentinel comment, then render a `difflib` unified diff. The
        # extended files are NOT subject to `_suffix_until_free`: the whole
        # point of the extend path is to hit the file the ledger already
        # records.
        extend_diffs: List[str] = []
        extend_targets_landed: List[str] = []
        for existing_rel, block, fallback_rel, fallback_full in executable_extends:
            try:
                existing_abs = (paths.repo_root / existing_rel).resolve()
                # Guard: the extend path must stay inside the repo so a
                # malformed ledger row cannot trick patch generation into
                # opening files outside the working tree.
                existing_abs.relative_to(paths.repo_root.resolve())
                old_body = existing_abs.read_text(encoding="utf-8")
            except (OSError, ValueError):
                # The recorded spec is gone (operator deleted it) — degrade
                # to a sibling new-file patch with the FULL generator output
                # (Codex review on PR #333). The bare extracted block would
                # land an invalid Playwright spec because it has no imports
                # or env setup. Suffix-collide-resolve so a stale name does
                # not block apply, then update the coverage override so the
                # ledger row points at the actually-shipped sibling.
                sibling_rel = _suffix_until_free(paths.repo_root, fallback_rel)
                resolved_specs.append((sibling_rel, fallback_full))
                _retarget_extend_override(
                    coverage_entries,
                    from_path=existing_rel,
                    to_path=sibling_rel,
                )
                continue
            new_body = _append_extend_block(old_body, block)
            extend_diff = _render_modify_diff(
                rel_path=existing_rel, old_body=old_body, new_body=new_body
            )
            if extend_diff:
                extend_diffs.append(extend_diff)
                extend_targets_landed.append(existing_rel)
        executable_targets = [rel for rel, _ in resolved_specs] + extend_targets_landed
        patch_parts: List[str] = []
        if resolved_specs:
            patch_parts.append(_render_multi_file_unified_diff(resolved_specs))
        patch_parts.extend(extend_diffs)
        patch_text = "".join(patch_parts)
        target_rel_path = executable_targets[0] if executable_targets else ""
    else:
        executable_targets = []
        target_rel = _suffix_until_free(
            paths.repo_root, skeleton.target_rel_path
        )
        patch_text = _render_unified_diff(rel_path=target_rel, new_body=skeleton.body)
        target_rel_path = target_rel

    digest = hashlib.sha1(patch_text.encode("utf-8")).hexdigest()[:16]
    patch_dir = paths.patches_dir / work_item_id
    patch_dir.mkdir(parents=True, exist_ok=True)
    patch_path = patch_dir / f"{digest}.patch"
    patch_path.write_text(patch_text, encoding="utf-8")
    rel_patch = str(patch_path.resolve().relative_to(paths.repo_root.resolve()))

    # Issue #320 (Codex P1) — drop a pending coverage manifest beside the patch.
    # The apply step (workflows.run_review_gate, --apply-patch) ingests it into
    # the ledger only after `git apply` lands the spec files; an unapplied or
    # rejected patch leaves the ledger untouched, so re-running implement-tests
    # regenerates the still-uncovered surface instead of being gated by a ghost.
    coverage_manifest_path: Optional[str] = None
    if coverage_entries:
        from .coverage_ledger import write_pending_manifest

        manifest_path = patch_dir / f"{digest}.coverage.json"
        try:
            write_pending_manifest(manifest_path, coverage_entries)
            coverage_manifest_path = str(
                manifest_path.resolve().relative_to(paths.repo_root.resolve())
            )
        except OSError as exc:
            events.write(
                "work_item.coverage_ledger_error",
                payload={"work_item_id": work_item_id, "error": str(exc)},
            )

    needs_decision = bool(generated_v2.get("needs_operator_decision"))
    next_status = "blocked" if needs_decision else "implementing"
    update_work_item_status(conn, events, work_item_id=work_item_id, status=next_status)
    artifact = register_work_item_artifact(
        conn,
        paths,
        events,
        work_item_id=work_item_id,
        kind="patch",
        path=rel_patch,
    )
    events.write(
        "work_item.patch_generated",
        actor="operator",
        payload={
            "work_item_id": work_item_id,
            "patch_path": rel_patch,
            "target_path": target_rel_path,
            "sha1_prefix": digest,
            "generated_at": now_iso(),
            "executable_tests_generated": has_executable_patch,
            "executable_targets": list(executable_targets),
            "generated_v2": generated_v2,
        },
    )

    return {
        "work_item_id": work_item_id,
        "status": next_status,
        "patch_path": rel_patch,
        "target_path": target_rel_path,
        "executable_targets": list(executable_targets),
        "artifacts": [artifact],
        "generated_v2": generated_v2,
        "executable_tests_generated": has_executable_patch,
        "idempotent_noop": False,
        "skipped_surfaces": generated_v2.get("skipped_surfaces", []),
        "coverage_manifest_path": coverage_manifest_path,
        "next_action": generated_v2.get("next_action"),
    }


def _try_generate_v2(
    conn: sqlite3.Connection,
    paths: RuntimePaths,
    events: EventLog,
    work_item_id: str,
    project_id: str,
) -> Dict[str, Any]:
    """Best-effort v2 generator. Returns counts; failures logged not raised.

    Issue #320 — ``conn`` + ``project_id`` let the generator gate on the
    coverage ledger and emit only the uncovered delta.
    """
    plan_json = paths.runtime_root / "plans" / work_item_id / "TEST-PLAN.json"
    if not plan_json.exists():
        return {
            "skipped": True,
            "reason": "no_test_plan_json",
            "needs_operator_decision": True,
            "next_action": "run `task plan` before implement-tests",
        }
    try:
        payload = json.loads(plan_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {
            "skipped": True,
            "reason": f"plan_json_unreadable: {exc}",
            "needs_operator_decision": True,
            "next_action": "repair TEST-PLAN.json",
        }
    items_raw = payload.get("items") or []
    if not items_raw:
        return {
            "skipped": True,
            "reason": "no_items",
            "needs_operator_decision": True,
            "next_action": "run analysis/plan and resolve candidate discovery",
        }

    from .generators.api import generate_api_tests, write_patch_artifact
    from .generators.ui import generate_ui_tests
    from .plan_v2 import PlanItem, validate_plan
    from .ids import ulid

    items: list = []
    for raw in items_raw:
        try:
            items.append(PlanItem(**{k: v for k, v in raw.items() if k in PlanItem.__dataclass_fields__}))
        except Exception:
            continue
    generate_now = [i for i in items if i.decision == "generate_now"]
    if not generate_now:
        return {
            "skipped": True,
            "reason": "no_generate_now_items",
            "total": len(items),
            "needs_operator_decision": True,
            "next_action": "approve at least one candidate with `task approve-candidate`",
        }

    findings = validate_plan(items)
    blockers = [f for f in findings if f.severity == "P0" and f.candidate_id in {i.candidate_id for i in generate_now}]
    if blockers:
        return {
            "skipped": True,
            "reason": "plan_validation_failed",
            "total": len(items),
            "needs_operator_decision": True,
            "next_action": "fix candidate assertions/test data before generation",
            "findings": [
                {"candidate_id": f.candidate_id, "severity": f.severity, "message": f.message}
                for f in blockers
            ],
        }

    # Issue #320 — idempotent generation: skip surfaces the project's coverage
    # ledger already records and generate only the delta. Skipped surfaces are
    # logged as auditable events. When nothing is left to generate the run is an
    # idempotent no-op — the caller must NOT fall back to a skeleton patch.
    from .coverage_ledger import find_existing_spec, partition_by_coverage, surface_key

    delta, skipped_surfaces = partition_by_coverage(
        conn, project_id=project_id, plan_items=generate_now
    )
    for surface in skipped_surfaces:
        events.write(
            "work_item.coverage_skipped",
            payload={"work_item_id": work_item_id, **surface},
        )
    # Issue #329 — split the delta into fresh (new spec file) and extend
    # (existing surface gained a new assertion bucket → append to the
    # already-recorded spec_path) buckets. The ledger row uniqueness key
    # ``(project, kind, key, assertion_kind)`` is preserved, so the extend
    # case appears as a delta item whose surface has prior coverage on a
    # *different* assertion_kind. The generator produces a full spec file
    # for both buckets; for extends we extract just the `test(...)` block
    # and emit a modify-file diff against the existing spec.
    extend_targets: Dict[str, str] = {}
    fresh_delta: List[Any] = []
    for item in delta:
        test_type = getattr(item, "test_type", "")
        try:
            key = surface_key(
                test_type,
                target_method=getattr(item, "target_method", None),
                target_path=getattr(item, "target_path", None),
                target_page=getattr(item, "target_page", None),
            )
        except Exception:
            fresh_delta.append(item)
            continue
        existing = find_existing_spec(
            conn,
            project_id=project_id,
            surface_kind=test_type,
            surface_key=key,
        )
        if existing:
            extend_targets[getattr(item, "candidate_id", "")] = existing
        else:
            fresh_delta.append(item)
    if not delta:
        return {
            "skipped": True,
            "reason": "all_surfaces_covered",
            "idempotent_noop": True,
            "skipped_surfaces": skipped_surfaces,
            "needs_operator_decision": False,
            "next_action": "no new surfaces to cover; ledger already up to date",
        }

    # Issue #98 — generators must honor `sut.tests_dir` so generated
    # files land where the configured runner will execute them.
    tests_dir = "tests"
    coverage_floor = False
    cfg = None
    try:
        from .config import load_or_default

        cfg = load_or_default(paths.repo_root)
        sut_cfg = cfg.raw.get("sut") or {}
        configured = sut_cfg.get("tests_dir")
        if isinstance(configured, str) and configured.strip():
            tests_dir = configured.strip()
        autonomy_cfg = cfg.raw.get("autonomy") or {}
        coverage_floor = bool(autonomy_cfg.get("coverage_floor", False))
    except Exception:
        # Config errors must not block generation; fall back to default.
        tests_dir = "tests"

    # Issue #360 — fan the test-family generators out into independent units,
    # one per family (API / UI). Each unit owns a DISJOINT output file set
    # (`tests/api/**` vs `tests/ui/**`), so the merge is a fixed-order
    # concatenation with no cross-family collision. The generators are pure
    # (they take no `conn`/`events`), so the worker threads stay DB/event-free
    # — the join barrier (this thread) keeps every ledger write + event.
    #
    # The generators are CPU-bound string templating today, so threading buys
    # no wall-clock under the GIL; the deliverable is a parallel-READY merge
    # contract (byte-stable, disjoint, single review gate) that materializes a
    # speedup once an implementer family is backed by an I/O- or model-bound
    # subagent. The final APPROVE stays single via `serialized_gate` (#361).
    from .autonomy.concurrency import build_concurrency_controller, fan_out

    api_items = [i for i in delta if i.test_type == "api"]
    ui_items = [i for i in delta if i.test_type == "ui"]
    family_names = ("api", "ui")
    family_thunks = [
        lambda: generate_api_tests(api_items, tests_dir=tests_dir, coverage_floor=coverage_floor),
        lambda: generate_ui_tests(ui_items, tests_dir=tests_dir, coverage_floor=coverage_floor),
    ]
    controller = build_concurrency_controller(cfg if cfg is not None else {})
    fan_results = fan_out(controller, "implementer", family_thunks)
    # Fixed-order join barrier: compose families in declaration order (api
    # before ui) regardless of thread completion order — keeps the merged patch
    # byte-stable. A failed unit fails the implement step LOUDLY: #360 must
    # never ship a patch missing a family. Graceful partial-failure degradation
    # is #362's concern, not this one — so re-raise the masked error here.
    family_specs: List[Any] = []
    for _family_name, result in zip(family_names, fan_results):
        if not result.ok:
            raise result.error  # fan_out guarantees `error` is set when ok is False
        family_specs.append(result.value)
    all_specs = [spec for specs in family_specs for spec in specs]

    # Issue #360/#362 — conflict detection. Assert units own disjoint output
    # paths (see `_detect_path_collisions`) so a future finer-grained fan-out
    # cannot silently merge two units onto the same spec path.
    _collisions = _detect_path_collisions(all_specs)
    if _collisions:
        raise UsageError(
            "implementer fan-out: families produced colliding output paths "
            f"{_collisions} — each unit must own a disjoint file set (#360)."
        )
    if not all_specs:
        return {
            "skipped": True,
            "reason": "no_supported_specs",
            "total": len(items),
            "needs_operator_decision": True,
            "next_action": "approve API or UI candidates supported by the generator",
        }

    # Issue #362 — a deterministic idempotency key per fan-out work-unit (one
    # per family). Surfaced on the emit event and the result so a rerun of the
    # same work item over the same approved surfaces is detectable as the same
    # unit. The on-disk dedup itself is already handled by the coverage ledger
    # (#320, skips already-covered surfaces) and `_suffix_until_free` (#223);
    # this makes that idempotency first-class and observable for the fan-out.
    idempotency_keys = {
        family: _implement_idempotency_key(work_item_id, family, specs)
        for family, specs in zip(family_names, family_specs)
    }

    run_id = ulid()
    out_dir = paths.runtime_root / "patches" / work_item_id / run_id
    manifest = write_patch_artifact(all_specs, output_dir=out_dir)
    # Issue #72 — build a single unified diff containing the executable
    # test files so review-gate --apply-patch creates them in the real
    # test tree, not just in the agentic-os-runtime bundle.
    #
    # Issue #329 — when a generated spec covers a surface that already has
    # ledger coverage on a different assertion bucket, do NOT emit a sibling
    # new-file diff. Extract the `test(...)` block from the generator
    # output and emit a modify-file diff against the existing spec instead.
    # Coverage entries for these items point at the *existing* spec_path so
    # `find_existing_spec` keeps returning that file on the next run.
    spec_files: List[tuple[str, str]] = []
    # Issue #329 — extend tuple carries (existing_rel_path, extracted_block,
    # fallback_rel_path, fallback_full_content). The fallback pair lets
    # ``implement_tests_for_work_item`` recover when the target spec was
    # deleted (or otherwise unreadable) by emitting the *full* generator
    # output — the bare extracted block has no imports / env setup and
    # would land an invalid Playwright spec on disk (Codex review).
    extend_files: List[tuple[str, str, str, str]] = []
    coverage_overrides: Dict[str, str] = {}  # candidate_id → existing_rel_path
    for spec in all_specs:
        cid = getattr(spec, "candidate_id", "")
        existing_path = extend_targets.get(cid)
        if existing_path:
            block = _extract_test_blocks(spec.content)
            if block:
                extend_files.append(
                    (existing_path, block, spec.relative_path, spec.content)
                )
                coverage_overrides[cid] = existing_path
                continue
            # Block extraction failed — degrade to the new-file path so the
            # surface still ships, even if as a sibling. The ledger will
            # record both spec_paths; future runs still dedupe by surface.
        spec_files.append((spec.relative_path, spec.content))
    events.write(
        "work_item.v2_generator_emitted",
        payload={
            "work_item_id": work_item_id,
            "run_id": run_id,
            "file_count": len(manifest["files"]),
            "idempotency_keys": idempotency_keys,
        },
    )
    return {
        "run_id": run_id,
        "output_dir": str(out_dir.relative_to(paths.repo_root)),
        "manifest": manifest,
        "needs_operator_decision": False,
        "next_action": "run review-gate, apply approved patch, then run-tests",
        # Issue #362 — per-work-unit idempotency keys (one per family).
        "idempotency_keys": idempotency_keys,
        # Issue #320 — surfaces skipped as already-covered, for the audit trail.
        "skipped_surfaces": skipped_surfaces,
        # Underscore-prefixed keys are consumed by
        # `implement_tests_for_work_item` and stripped before persistence.
        # Issue #223 — pass (rel_path, body) tuples so the caller can rewrite
        # paths when the target already exists, then render the unified diff
        # against the resolved (suffixed) paths.
        "_executable_specs": list(spec_files),
        # Issue #329 — extend-in-place tuples (existing_rel_path, block) the
        # caller renders as a modify-file diff. Kept separate from
        # ``_executable_specs`` so ``_suffix_until_free`` is never applied to
        # them: extensions must land on the existing file.
        "_executable_extends": list(extend_files),
        # Issue #319 — hand the caller (which holds conn + project_id) the plan
        # items and generated specs so it can populate the coverage ledger.
        # Issue #320 — only the generated delta is recorded; covered surfaces
        # were skipped above.
        # Issue #329 — when a delta item was rerouted into the extend path,
        # its ledger row must record the existing shared spec_path, not the
        # path the generator would have used. ``coverage_overrides`` lets the
        # caller swap ``GeneratedTest.relative_path`` for those candidates
        # before building the manifest.
        "_coverage": {
            "plan_items": list(delta),
            "generated_tests": list(all_specs),
            "run_id": run_id,
            "spec_path_overrides": dict(coverage_overrides),
        },
    }


def build_skeleton_patch(
    *,
    work_item_id: str,
    title: str,
    priority: str,
    sut_root: str,
    plan_text: str,
) -> PatchPlan:
    buckets = _extract_bucket_titles(plan_text)
    body = _render_skeleton_body(
        work_item_id=work_item_id,
        title=title,
        priority=priority,
        sut_root=sut_root,
        buckets=buckets,
    )
    target_rel = f"{SKELETON_REL_DIR}/{work_item_id}.spec.md"
    return PatchPlan(target_rel_path=target_rel, body=body)


def _extract_bucket_titles(plan_text: str) -> List[Dict[str, List[str]]]:
    """Pull `### <Bucket>` headings and their bullet lines from the plan."""
    buckets: List[Dict[str, Any]] = []
    current: Dict[str, Any] | None = None
    for line in plan_text.splitlines():
        heading = re.match(r"^###\s+(.+?)\s*$", line)
        if heading:
            if current is not None:
                buckets.append(current)
            current = {"title": heading.group(1).strip(), "items": []}
            continue
        if current is None:
            continue
        bullet = re.match(r"^\s*[-*]\s+(.+?)\s*$", line)
        if bullet:
            text = bullet.group(1).strip()
            if text:
                current["items"].append(text)
    if current is not None:
        buckets.append(current)
    return buckets


def _render_skeleton_body(
    *,
    work_item_id: str,
    title: str,
    priority: str,
    sut_root: str,
    buckets: List[Dict[str, Any]],
) -> str:
    safe_title = title.replace("`", "").strip() or work_item_id
    lines: List[str] = [
        f"# Test skeleton — {safe_title}",
        "",
        f"- Task id: `{work_item_id}`",
        f"- Priority: `{priority}`",
        f"- SUT root: `{sut_root}`",
        "",
        (
            "This file is an operator-reviewable skeleton produced by "
            "`task implement-tests`. It must not introduce trivial assertions, "
            "weaken existing assertions, or silently skip scenarios. Real tests "
            "(API/UI) should be added in dedicated files once the operator "
            "approves the implementation patch."
        ),
        "",
        "## Buckets carried from TEST-PLAN.md",
        "",
    ]
    if not buckets:
        lines.append("_No buckets parsed from TEST-PLAN.md._")
    else:
        for bucket in buckets:
            lines.append(f"### {bucket['title']}")
            lines.append("")
            items = bucket.get("items") or []
            if not items:
                lines.append("- (no candidates listed)")
            else:
                for item in items:
                    lines.append(f"- [ ] {item}")
            lines.append("")
    lines.extend(
        [
            "## Review checklist (operator)",
            "",
            "- [ ] Patch was generated from the current TEST-PLAN.md, not a stale copy.",
            "- [ ] No bucket items were silently dropped.",
            "- [ ] No existing tests were modified by this patch.",
            "- [ ] `review-gate --scope assertion` was run and approved.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _suffix_until_free(repo_root: Path, rel_path: str) -> str:
    """Return ``rel_path`` if it does not exist on disk, otherwise append the
    smallest numeric suffix that keeps the path collision-free.

    A target like ``tests/api/foo.spec.ts`` becomes ``tests/api/foo.2.spec.ts``
    on the first collision, ``tests/api/foo.3.spec.ts`` on the second, etc.
    Files without a recognizable test extension fall back to ``<stem>.<n>``.
    """
    target = repo_root / rel_path
    if not target.exists():
        return rel_path
    path = Path(rel_path)
    parent = path.parent
    name = path.name
    spec_match = re.match(r"^(?P<stem>.+?)(?P<spec>\.spec)(?P<ext>\.[A-Za-z0-9]+)$", name)
    if spec_match:
        stem = spec_match.group("stem")
        spec = spec_match.group("spec")
        ext = spec_match.group("ext")
        builder = lambda n: f"{stem}.{n}{spec}{ext}"
    else:
        # Generic fallback: insert ``.<n>`` before the final extension.
        stem = path.stem
        ext = path.suffix
        builder = lambda n: f"{stem}.{n}{ext}" if ext else f"{stem}.{n}"
    n = 2
    while True:
        candidate = parent / builder(n)
        if not (repo_root / candidate).exists():
            return str(candidate)
        n += 1


def _render_unified_diff(*, rel_path: str, new_body: str) -> str:
    """Render a minimal additive unified diff that `git apply` accepts."""
    new_lines = new_body.split("\n")
    if new_lines and new_lines[-1] == "":
        new_lines = new_lines[:-1]
    line_count = len(new_lines)
    if line_count == 0:
        raise UsageError("refusing to build empty patch")
    header = [
        f"diff --git a/{rel_path} b/{rel_path}",
        "new file mode 100644",
        "--- /dev/null",
        f"+++ b/{rel_path}",
        f"@@ -0,0 +1,{line_count} @@",
    ]
    body_lines = [f"+{line}" for line in new_lines]
    return "\n".join(header + body_lines) + "\n"


_EXTEND_SENTINEL = "// agentic-os:extend"


def _extract_test_blocks(generated_content: str) -> str:
    """Return the `test(...)` declarations from a generator output.

    Issue #329 — the in-place extension path needs to append the assertion
    block(s) the generator just produced to an existing spec without
    duplicating its imports, env-var guards, or `test.use(...)` lines.
    The Playwright templates always emit one or more `test(<title>,
    async (...) => { ... });` blocks starting at column 0 after the setup
    section, so we slice the generated content from the first line that
    begins with ``test(`` through end of file. Returns an empty string
    when the marker is absent, so the caller can fall back to the
    new-file path.
    """
    match = re.search(r"^test\(", generated_content, re.MULTILINE)
    if match is None:
        return ""
    block = generated_content[match.start():]
    return block.rstrip() + "\n"


def _append_extend_block(old_body: str, block: str) -> str:
    """Append a generator-produced `test(...)` block to an existing spec.

    Issue #329 — the operator-visible separator is a sentinel comment so
    re-runs of `find_existing_spec` can spot prior extensions without an
    AST parser, and so reviewers can grep for accumulated buckets. The
    appended block is always preceded by a blank line for readability.
    """
    if not block.strip():
        return old_body
    base = old_body if old_body.endswith("\n") else old_body + "\n"
    return base + f"\n{_EXTEND_SENTINEL}\n" + block


def _retarget_extend_override(
    coverage_entries: List[Dict[str, Any]],
    *,
    from_path: str,
    to_path: str,
) -> None:
    """Re-point an extend candidate's coverage entry at the fallback sibling.

    Issue #329 — when the existing spec is unreadable we fall back to a
    full sibling new-file patch. The coverage entry was overridden to
    point at the (now-stale) shared path; rewrite it to the sibling that
    actually shipped, so the next ``find_existing_spec`` lookup resolves
    to a file that exists on disk.
    """
    for entry in coverage_entries:
        if entry.get("spec_path") == from_path:
            entry["spec_path"] = to_path


def _render_modify_diff(*, rel_path: str, old_body: str, new_body: str) -> str:
    """Render a modify-file unified diff that `git apply` accepts.

    Issue #329 — uses ``difflib.unified_diff`` so the hunk headers carry
    correct context and `git apply` can locate the change. A `diff --git`
    header is prepended so the diff round-trips through the same code
    path as new-file diffs.
    """
    if old_body == new_body:
        return ""
    import difflib

    old_lines = old_body.splitlines(keepends=True)
    new_lines = new_body.splitlines(keepends=True)
    diff_iter = difflib.unified_diff(
        old_lines,
        new_lines,
        fromfile=f"a/{rel_path}",
        tofile=f"b/{rel_path}",
        n=3,
    )
    body = "".join(diff_iter)
    if not body:
        return ""
    # Make sure the diff ends with a newline so concatenation does not glue
    # the next file header to the last hunk line.
    if not body.endswith("\n"):
        body += "\n"
    return f"diff --git a/{rel_path} b/{rel_path}\n{body}"


def _render_multi_file_unified_diff(files: List[tuple[str, str]]) -> str:
    """Concatenate additive new-file diffs for every (rel_path, body) entry.

    Used by issue #72 so the patch returned by `implement-tests` carries
    the real executable test files. The diff `git apply` consumes is the
    plain concatenation of individual file diffs — each file starts a
    new `diff --git` header.
    """
    if not files:
        raise UsageError("refusing to build empty patch")
    parts: List[str] = []
    for rel_path, body in files:
        parts.append(_render_unified_diff(rel_path=rel_path, new_body=body))
    return "".join(parts)
